name: Device issue
description: Device or entity unavailable / Missing entity / 设备或实体不可用 / 缺少实体
body:
  - type: input
    validations:
      required: true
    attributes:
      label: Device model
      placeholder: brand.device.model

  - type: input
    attributes:
      label: Component version
      placeholder: 0.7.x

  - type: input
    attributes:
      label: HA core version
      placeholder: 2022.12.x
      description: |
        > [⚙️ Settings](https://my.home-assistant.io/redirect/config) > [ℹ️️ About](https://my.home-assistant.io/redirect/info)

  - type: dropdown
    attributes:
      label: Integrated mode
      options:
        - Automatic (自动模式)
        - Local (本地模式)
        - Cloud (云端模式)
        - Token

  - type: textarea
    attributes:
      label: The problem

  - type: textarea
    attributes:
      label: Entity attributes
      description: |
        > [🔨 Developer tools](https://my.home-assistant.io/redirect/developer_states) > [ℹ️ State](https://my.home-assistant.io/redirect/developer_states) > 🔍 Filter (Entity with most attributes)
      render: yaml

  - type: textarea
    attributes:
      label: Home Assistant Logs
      description: |
        > [⚙️ Settings](https://my.home-assistant.io/redirect/config) > [⚙️ System](https://my.home-assistant.io/redirect/system_dashboard) > [✍️ Logs](https://my.home-assistant.io/redirect/logs)
      render: txt
