send_command:
  description: Send miio command.
  fields:
    entity_id:
      description: ID of the entity.
      example: "light.yeelight_living_e92c"
    method:
      description: Method of the command.
      example: set_power
    params:
      description: Params for the method.
      example: ['on']

get_properties:
  description: Get miot properties.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
    mapping:
      description: Mapping for properties.
      example: "{'power': {'siid': 2, 'piid': 1}}"

set_property:
  description: Set miot property.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
    field:
      description: Field of property.
      example: "air_conditioner.on"
    value:
      description: Value of property.
      example: True

set_miot_property:
  description: Set miot property by siid/piid.
  fields:
    entity_id:
      description: ID of the entity.
      example: "climate.xiaomi_mc5_374e"
    siid:
      description: Miot service ID.
      example: 2
    piid:
      description: Miot property ID.
      example: 1
    value:
      description: Miot property value.
      example: True

call_action:
  description: Call miot action.
  fields:
    entity_id:
      description: ID of the entity.
      example: "media_player.xiaoai_x08c"
    siid:
      description: Miot service ID.
      example: 3
    aiid:
      description: Miot action ID.
      example: 5
    params:
      description: Miot action params.
      example: "['Turn on light', 1]"
